apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs-pvc
  namespace: codens
spec:
  accessModes: [ ReadWriteOnce ]
  storageClassName: do-block-storage 
  resources:
    requests:
      storage: 1Gi
  