

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-deploy
  namespace: codens
  labels:
    name: cs-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cs-po
  template:
    metadata:
      name: cs-po
      labels:
        name: cs-po
    spec:
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: cs-pvc
      containers:
      - name: cs-container
        image: linuxserver/code-server:amd64-4.17.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: cs-cm
        - secretRef:
            name: cs-cm
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: data-vol
          mountPath: /config/workspace

---
apiVersion: v1
kind: Service
metadata:
  name: cs-svc
  namespace: codens
spec:
  type: ClusterIP
  selector:
    name: cs-po
  ports:
  - port: 8443
    targetPort: 8443

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cs-ing
  namespace: codens
spec:
  ingressClassName: nginx
  rules:
  - host: code-188.166.196.227.nip.io
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: cs-svc
            port:
              number: 8443