apiVersion: v1 
kind: Service 
metadata: 
  name: bggapp-svc
  namespace: bggns
  labels:
      app: bgg 
      tier: web
      name: bggapp-svc 
spec: 
  type: NodePort 
  selector:
    app: bgg 
    tier: web
    name: bggapp-po 
  ports:
  - port: 8080
    targetPort: 3000