apiVersion: v1
kind: pod
metadata:
  name: dov-po
  namespace: myns
  labels:
    version: v1
    app: dov
    dept: eng
spec:
  containers:
    name: dov-container
    image: docker.io/meiannn/dovbear:v1
    imagePullPolicy: IfNotPresent
    ports:
    #EXPOSE
    - containerPort: 3000


  


    