apiVersion: v1 
kind: ConfigMap 
metadata:
  name: minio-cm
  namespace: minions 
data: 
  MINIO_ROOT_USER: admin 

---
apiVersion: v1 
kind: Secret
metadata: 
  name: minio-secret 
  namespace: minions
type: Opaque
data: 
                  #somepassword
  BGG_DB_PASSWORD: c29tZXBhc3N3b3Jk